### ISSUE TITLE
Compile issues on FFmpeg 7.1.1

### ISSUE THREAD

**Issue by jpietek** [amagimedia/avplumber#10]
Got:

```
src/nodes/filters.cpp:461:30: error: ‘const AVFilterLink’ {aka ‘const struct AVFilterLink’} has no member named ‘frame_rate’
  461 |             return outlink_->frame_rate;  
```

We could fix it with?
```
-            return outlink_->frame_rate;
+            return av_inv_q(outlink_->time_base);
```

AVFilterLink link->hw_frames_ctx also is not present now, commented out realPixelFormat and hwaccel init to compile, but hwaccel won't work on newest ffmpegs, headers of AVFilterLink has changed.

**Comment by teodly** [comment]
Fixed by https://github.com/amagimedia/avplumber/commit/c4b393ccb5f0992c95565d417ac40b2e8f2c5752 , compiles on Fedora with FFmpeg 7.1
